# Generated by Django 5.0.6 on 2024-05-27 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.PositiveIntegerField(max_length=5, primary_key=True, serialize=False)),
                ('NombreCliente', models.CharField(max_length=100)),
                ('RutCliente', models.CharField(max_length=100)),
                ('Gmail', models.CharField(max_length=100)),
                ('Contrasenna', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('NombreTipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.PositiveIntegerField(max_length=5, primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=100)),
                ('Precio', models.PositiveIntegerField()),
                ('Descripcion', models.CharField(max_length=100)),
                ('Tipo_roducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api.tipoproducto')),
            ],
        ),
    ]
