# Generated by Django 5.0.6 on 2024-05-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='idTipo',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
